### PR TITLE
fix: remove hack for comma-less ranges support

### PR DESCRIPTION
**Pull request by adrukh**

### CODE REVIEW

**Comment by darscan** [comment]
Tests need to be rolled back too :)

**Comment by darscan** [comment]
Something I'm not clear about: The description for this lib is "A semver parser that uses RubyGem's semantics with node-semver's api". If it supports "node-semver's api", then perhaps it needs to be able to handle comma-less ranges, as NPM does? Just a thought.

**Comment by adrukh** [comment]
I think that 'speaking native RubyGems' is more important in this context, rather than trying to apply semantics from newer ecosystems which may later create conflicts?

**Comment by darscan** [comment]
Gotcha

**Pull request merged**
